/**
 * Test suite for FilePatcher
 */

import { assertEquals, assertStringIncludes } from "@std/assert";
import { FilePatcher } from "../src/file-patcher.ts";
import type { MetadataFile } from "../src/repository-manager.ts";

Deno.test("FilePatcher - patchKeywords in desktop file", () => {
  const patcher = new FilePatcher();
  const file: MetadataFile = {
    path: "/test/app.desktop",
    type: "desktop",
    content: `[Desktop Entry]
Name=Test App
Exec=test-app
`,
  };

  const keywords = ["test", "sample", "demo"];
  const result = patcher.patchKeywords(file, keywords);

  assertStringIncludes(result, "Keywords=test;sample;demo;");
  assertStringIncludes(result, "[Desktop Entry]");
});

Deno.test(
  "FilePatcher - patchKeywords merges keywords in desktop file when they exist",
  () => {
    const patcher = new FilePatcher();
    const file: MetadataFile = {
      path: "/test/app.desktop",
      type: "desktop",
      content: `[Desktop Entry]
Name=Test App
Keywords=old;existing;
Exec=test-app
`,
    };

    const keywords = ["new", "keywords"];
    const result = patcher.patchKeywords(file, keywords);

    // Should merge old and new keywords
    assertStringIncludes(result, "old");
    assertStringIncludes(result, "existing");
    assertStringIncludes(result, "new");
    assertStringIncludes(result, "keywords");
    assertEquals(result.match(/Keywords=/g)?.length, 1);
  }
);

Deno.test("FilePatcher - patchKeywords in XML file", () => {
  const patcher = new FilePatcher();
  const file: MetadataFile = {
    path: "/test/app.metainfo.xml",
    type: "metainfo",
    content: `<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop">
  <id>com.example.App</id>
  <name>Test App</name>
</component>
`,
  };

  const keywords = ["xml", "test", "metadata"];
  const result = patcher.patchKeywords(file, keywords);

  assertStringIncludes(result, "<keywords>");
  assertStringIncludes(result, "<keyword>xml</keyword>");
  assertStringIncludes(result, "<keyword>test</keyword>");
  assertStringIncludes(result, "<keyword>metadata</keyword>");
  assertStringIncludes(result, "</keywords>");
});

Deno.test("FilePatcher - patchSummary in XML file", () => {
  const patcher = new FilePatcher();
  const file: MetadataFile = {
    path: "/test/app.metainfo.xml",
    type: "metainfo",
    content: `<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop">
  <id>com.example.App</id>
  <name>Test App</name>
</component>
`,
  };

  const summary = "A test application for demonstration";
  const result = patcher.patchSummary(file, summary);

  assertStringIncludes(result, "<summary>");
  assertStringIncludes(result, summary);
  assertStringIncludes(result, "</summary>");
});

Deno.test("FilePatcher - patchSummary skips desktop files", () => {
  const patcher = new FilePatcher();
  const originalContent = `[Desktop Entry]
Name=Test App
`;
  const file: MetadataFile = {
    path: "/test/app.desktop",
    type: "desktop",
    content: originalContent,
  };

  const summary = "This should not be added";
  const result = patcher.patchSummary(file, summary);

  assertEquals(result, originalContent);
});

Deno.test("FilePatcher - patchDescription with XML-formatted content", () => {
  const patcher = new FilePatcher();
  const file: MetadataFile = {
    path: "/test/app.metainfo.xml",
    type: "metainfo",
    content: `<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop">
    <id>com.example.App</id>
    <name>Test App</name>
    <summary>A test application</summary>
</component>
`,
  };

  // Description with proper XML tags (as generated by MetadataGenerator)
  const description = `<p>
  This is a comprehensive test application for demonstration purposes.
</p>
<ul>
  <li>Feature one</li>
  <li>Feature two</li>
  <li>Feature three</li>
</ul>
<p>
  Additional information with <em>emphasis</em> and <code>code</code> tags.
</p>`;

  const result = patcher.patchDescription(file, description);

  // Verify the XML tags are preserved (not escaped)
  assertStringIncludes(result, "<description>");
  assertStringIncludes(result, "<p>");
  assertStringIncludes(result, "<ul>");
  assertStringIncludes(result, "<li>Feature one</li>");
  assertStringIncludes(result, "<em>emphasis</em>");
  assertStringIncludes(result, "<code>code</code>");
  assertStringIncludes(result, "</description>");

  // Verify tags are NOT escaped
  assertEquals(result.includes("&lt;p&gt;"), false);
  assertEquals(result.includes("&lt;ul&gt;"), false);
});

Deno.test("FilePatcher - preserves NOTE disclaimer", () => {
  const patcher = new FilePatcher();
  const original = `<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop">
  <id>net.filebot.FileBot</id>
  <name>FileBot</name>
  <summary>Ultimate TV and movie renamer</summary>
   <description>
    <p>FileBot is the ultimate tool for renaming and organizing your movies, TV shows and Anime. Match and rename media files against online databases, download artwork and cover images, fetch subtitles, write metadata, and more, all at once in matter of seconds. It's smart and just works.</p>
    <p>NOTE: This application is not verified by, affiliated with, or supported by Point Planck Limited.</p>
  </description>
</component>
`;
  const file: MetadataFile = {
    path: "/test/app.metainfo.xml",
    type: "metainfo",
    content: original,
  };
  const newDescription = `<p>Updated description body with new content.</p>`;
  const result = patcher.patchDescription(file, newDescription);
  // Ensure disclaimer preserved
  assertStringIncludes(
    result,
    "NOTE: This application is not verified by, affiliated with, or supported by Point Planck Limited."
  );
  assertStringIncludes(result, "Updated description body with new content.");
});

Deno.test("FilePatcher - patchDescription skips desktop files", () => {
  const patcher = new FilePatcher();
  const originalContent = `[Desktop Entry]
Name=Test App
`;
  const file: MetadataFile = {
    path: "/test/app.desktop",
    type: "desktop",
    content: originalContent,
  };

  const description = "This should not be added";
  const result = patcher.patchDescription(file, description);

  assertEquals(result, originalContent);
});

Deno.test("FilePatcher - hasKeywords detects keywords in desktop file", () => {
  const patcher = new FilePatcher();
  const file: MetadataFile = {
    path: "/test/app.desktop",
    type: "desktop",
    content: `[Desktop Entry]
Name=Test App
Keywords=test;sample;demo;
Exec=test-app
`,
  };

  assertEquals(patcher.hasKeywords(file), true);
});

Deno.test("FilePatcher - hasKeywords detects no keywords in desktop file", () => {
  const patcher = new FilePatcher();
  const file: MetadataFile = {
    path: "/test/app.desktop",
    type: "desktop",
    content: `[Desktop Entry]
Name=Test App
Exec=test-app
`,
  };

  assertEquals(patcher.hasKeywords(file), false);
});

Deno.test("FilePatcher - hasKeywords detects keywords in XML file", () => {
  const patcher = new FilePatcher();
  const file: MetadataFile = {
    path: "/test/app.metainfo.xml",
    type: "metainfo",
    content: `<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop">
  <id>com.example.App</id>
  <name>Test App</name>
  <keywords>
    <keyword>test</keyword>
    <keyword>sample</keyword>
  </keywords>
</component>
`,
  };

  assertEquals(patcher.hasKeywords(file), true);
});

Deno.test("FilePatcher - hasKeywords detects no keywords in XML file", () => {
  const patcher = new FilePatcher();
  const file: MetadataFile = {
    path: "/test/app.metainfo.xml",
    type: "metainfo",
    content: `<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop">
  <id>com.example.App</id>
  <name>Test App</name>
</component>
`,
  };

  assertEquals(patcher.hasKeywords(file), false);
});

Deno.test("FilePatcher - getExistingKeywords from desktop file", () => {
  const patcher = new FilePatcher();
  const file: MetadataFile = {
    path: "/test/app.desktop",
    type: "desktop",
    content: `[Desktop Entry]
Name=Test App
Keywords=test;sample;demo;
Exec=test-app
`,
  };

  const keywords = patcher.getExistingKeywords(file);
  assertEquals(keywords, ["test", "sample", "demo"]);
});

Deno.test("FilePatcher - getExistingKeywords from XML file", () => {
  const patcher = new FilePatcher();
  const file: MetadataFile = {
    path: "/test/app.metainfo.xml",
    type: "metainfo",
    content: `<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop">
  <id>com.example.App</id>
  <keywords>
    <keyword>test</keyword>
    <keyword>sample</keyword>
    <keyword>demo</keyword>
  </keywords>
</component>
`,
  };

  const keywords = patcher.getExistingKeywords(file);
  assertEquals(keywords, ["test", "sample", "demo"]);
});

Deno.test("FilePatcher - mergeKeywords adds new keywords", () => {
  const patcher = new FilePatcher();
  const existing = ["test", "sample"];
  const newKeywords = ["demo", "example"];

  const merged = patcher.mergeKeywords(existing, newKeywords);
  assertEquals(merged, ["test", "sample", "demo", "example"]);
});

Deno.test("FilePatcher - mergeKeywords avoids duplicates", () => {
  const patcher = new FilePatcher();
  const existing = ["test", "sample", "demo"];
  const newKeywords = ["demo", "example", "TEST"];

  const merged = patcher.mergeKeywords(existing, newKeywords);
  // "demo" and "TEST" should not be duplicated (case-insensitive)
  assertEquals(merged, ["test", "sample", "demo", "example"]);
});

Deno.test("FilePatcher - patchKeywords merges with existing keywords in desktop file", () => {
  const patcher = new FilePatcher();
  const file: MetadataFile = {
    path: "/test/app.desktop",
    type: "desktop",
    content: `[Desktop Entry]
Name=Test App
Keywords=existing;keywords;
Exec=test-app
`,
  };

  const newKeywords = ["new", "keywords", "here"];
  const result = patcher.patchKeywords(file, newKeywords);

  // Should contain both existing and new keywords
  assertStringIncludes(result, "existing");
  assertStringIncludes(result, "new");
  assertStringIncludes(result, "here");
  // But "keywords" should only appear once (case-insensitive deduplication)
  assertEquals(result.match(/Keywords=/g)?.length, 1);
});

Deno.test("FilePatcher - patchKeywords merges with existing keywords in XML file", () => {
  const patcher = new FilePatcher();
  const file: MetadataFile = {
    path: "/test/app.metainfo.xml",
    type: "metainfo",
    content: `<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop">
  <id>com.example.App</id>
  <keywords>
    <keyword>existing</keyword>
    <keyword>keywords</keyword>
  </keywords>
</component>
`,
  };

  const newKeywords = ["new", "keywords", "here"];
  const result = patcher.patchKeywords(file, newKeywords);

  // Should contain both existing and new keywords
  assertStringIncludes(result, "<keyword>existing</keyword>");
  assertStringIncludes(result, "<keyword>new</keyword>");
  assertStringIncludes(result, "<keyword>here</keyword>");
  // But "keywords" should only appear once (case-insensitive deduplication)
  const keywordMatches = result.match(/<keyword>keywords<\/keyword>/g);
  assertEquals(keywordMatches?.length, 1);
});
